version: "3.8"

services:
  web:
    volumes:
      # Mounts your local code into the container for live-reloading
      - .:/app
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_DEBUG=1
